// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {steamgriddb} from '../models';
import {version} from '../models';

export function AddGameSetup(arg1:config.GameSetup):Promise<void>;

export function CancelPairing():Promise<void>;

export function ClearImageCache():Promise<void>;

export function ConfirmPairing(arg1:string):Promise<void>;

export function ConnectAgent(arg1:string):Promise<void>;

export function DeleteGame(arg1:string,arg2:number):Promise<void>;

export function DisconnectAgent():Promise<void>;

export function GetAgentInstallPath():Promise<string>;

export function GetArtworkPreview(arg1:string):Promise<string>;

export function GetCacheSize():Promise<number>;

export function GetConnectionStatus():Promise<main.ConnectionStatus>;

export function GetDiscoveredAgents():Promise<Array<main.DiscoveredAgentInfo>>;

export function GetGameSetups():Promise<Array<config.GameSetup>>;

export function GetGrids(arg1:number,arg2:steamgriddb.ImageFilters,arg3:number):Promise<Array<steamgriddb.ImageData>>;

export function GetHeroes(arg1:number,arg2:steamgriddb.ImageFilters,arg3:number):Promise<Array<steamgriddb.ImageData>>;

export function GetHubInfo():Promise<main.HubInfo>;

export function GetHubName():Promise<string>;

export function GetIcons(arg1:number,arg2:steamgriddb.ImageFilters,arg3:number):Promise<Array<steamgriddb.ImageData>>;

export function GetImageCacheEnabled():Promise<boolean>;

export function GetInstalledGames(arg1:string):Promise<Array<main.InstalledGame>>;

export function GetLogos(arg1:number,arg2:steamgriddb.ImageFilters,arg3:number):Promise<Array<steamgriddb.ImageData>>;

export function GetSteamGridDBAPIKey():Promise<string>;

export function GetVersion():Promise<version.Info>;

export function OpenCacheFolder():Promise<void>;

export function RefreshDiscovery():Promise<Array<main.DiscoveredAgentInfo>>;

export function RemoveGameSetup(arg1:string):Promise<void>;

export function SearchGames(arg1:string):Promise<Array<steamgriddb.SearchResult>>;

export function SelectArtworkFile():Promise<main.ArtworkFileResult>;

export function SelectFolder():Promise<string>;

export function SetHubName(arg1:string):Promise<void>;

export function SetImageCacheEnabled(arg1:boolean):Promise<void>;

export function SetSteamGridDBAPIKey(arg1:string):Promise<void>;

export function UpdateGameArtwork(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function UpdateGameSetup(arg1:string,arg2:config.GameSetup):Promise<void>;

export function UploadGame(arg1:string):Promise<void>;
