// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGameSetup(arg1) {
  return window['go']['main']['App']['AddGameSetup'](arg1);
}

export function CancelPairing() {
  return window['go']['main']['App']['CancelPairing']();
}

export function ClearImageCache() {
  return window['go']['main']['App']['ClearImageCache']();
}

export function ConfirmPairing(arg1) {
  return window['go']['main']['App']['ConfirmPairing'](arg1);
}

export function ConnectAgent(arg1) {
  return window['go']['main']['App']['ConnectAgent'](arg1);
}

export function DeleteGame(arg1, arg2) {
  return window['go']['main']['App']['DeleteGame'](arg1, arg2);
}

export function DisconnectAgent() {
  return window['go']['main']['App']['DisconnectAgent']();
}

export function GetAgentInstallPath() {
  return window['go']['main']['App']['GetAgentInstallPath']();
}

export function GetCacheSize() {
  return window['go']['main']['App']['GetCacheSize']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetDiscoveredAgents() {
  return window['go']['main']['App']['GetDiscoveredAgents']();
}

export function GetGameSetups() {
  return window['go']['main']['App']['GetGameSetups']();
}

export function GetGrids(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetGrids'](arg1, arg2, arg3);
}

export function GetHeroes(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetHeroes'](arg1, arg2, arg3);
}

export function GetIcons(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetIcons'](arg1, arg2, arg3);
}

export function GetImageCacheEnabled() {
  return window['go']['main']['App']['GetImageCacheEnabled']();
}

export function GetInstalledGames(arg1) {
  return window['go']['main']['App']['GetInstalledGames'](arg1);
}

export function GetLogos(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLogos'](arg1, arg2, arg3);
}

export function GetSteamGridDBAPIKey() {
  return window['go']['main']['App']['GetSteamGridDBAPIKey']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenCacheFolder() {
  return window['go']['main']['App']['OpenCacheFolder']();
}

export function OpenCachedImage(arg1, arg2) {
  return window['go']['main']['App']['OpenCachedImage'](arg1, arg2);
}

export function ProxyImage(arg1) {
  return window['go']['main']['App']['ProxyImage'](arg1);
}

export function ProxyImageCached(arg1, arg2) {
  return window['go']['main']['App']['ProxyImageCached'](arg1, arg2);
}

export function RefreshDiscovery() {
  return window['go']['main']['App']['RefreshDiscovery']();
}

export function RemoveGameSetup(arg1) {
  return window['go']['main']['App']['RemoveGameSetup'](arg1);
}

export function SearchGames(arg1) {
  return window['go']['main']['App']['SearchGames'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetImageCacheEnabled(arg1) {
  return window['go']['main']['App']['SetImageCacheEnabled'](arg1);
}

export function SetSteamGridDBAPIKey(arg1) {
  return window['go']['main']['App']['SetSteamGridDBAPIKey'](arg1);
}

export function UpdateGameSetup(arg1, arg2) {
  return window['go']['main']['App']['UpdateGameSetup'](arg1, arg2);
}

export function UploadGame(arg1) {
  return window['go']['main']['App']['UploadGame'](arg1);
}
