run:
  timeout: 5m
  build-tags:
    - webkit2_41

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - gocritic
    - misspell
    - revive

issues:
  exclude-dirs:
    - steam-shortcut-manager/vendor
    - frontend/dist
    - node_modules
    - wailsjs

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-checks:
      - hugeParam
