// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteShortcut(arg1, arg2) {
  return window['go']['main']['App']['DeleteShortcut'](arg1, arg2);
}

export function DisconnectHub() {
  return window['go']['main']['App']['DisconnectHub']();
}

export function GetAuthorizedHubs() {
  return window['go']['main']['App']['GetAuthorizedHubs']();
}

export function GetInstallPath() {
  return window['go']['main']['App']['GetInstallPath']();
}

export function GetShortcuts(arg1) {
  return window['go']['main']['App']['GetShortcuts'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSteamUsers() {
  return window['go']['main']['App']['GetSteamUsers']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function RevokeHub(arg1) {
  return window['go']['main']['App']['RevokeHub'](arg1);
}

export function SelectInstallPath() {
  return window['go']['main']['App']['SelectInstallPath']();
}

export function SetAcceptConnections(arg1) {
  return window['go']['main']['App']['SetAcceptConnections'](arg1);
}

export function SetInstallPath(arg1) {
  return window['go']['main']['App']['SetInstallPath'](arg1);
}

export function SetName(arg1) {
  return window['go']['main']['App']['SetName'](arg1);
}
