// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {version} from '../models';

export function DeleteShortcut(arg1:string,arg2:number):Promise<void>;

export function DisconnectHub():Promise<void>;

export function GetAuthorizedHubs():Promise<Array<main.AuthorizedHubInfo>>;

export function GetConsoleLogEnabled():Promise<boolean>;

export function GetInstallPath():Promise<string>;

export function GetShortcuts(arg1:string):Promise<Array<main.ShortcutInfo>>;

export function GetStatus():Promise<main.AgentStatus>;

export function GetSteamUsers():Promise<Array<main.SteamUserInfo>>;

export function GetTelemetryEnabled():Promise<boolean>;

export function GetTelemetryInterval():Promise<number>;

export function GetVersion():Promise<version.Info>;

export function RevokeHub(arg1:string):Promise<void>;

export function SelectInstallPath():Promise<string>;

export function SetAcceptConnections(arg1:boolean):Promise<void>;

export function SetConsoleLogEnabled(arg1:boolean):Promise<void>;

export function SetInstallPath(arg1:string):Promise<void>;

export function SetName(arg1:string):Promise<void>;

export function SetTelemetryEnabled(arg1:boolean):Promise<void>;

export function SetTelemetryInterval(arg1:number):Promise<void>;
