// See https://kit.svelte.dev/docs/types#app
// for information about these interfaces
declare global {
	namespace App {
		// interface Error {}
		// interface Locals {}
		// interface PageData {}
		// interface PageState {}
		// interface Platform {}
	}

	// Wails runtime
	const runtime: {
		EventsOn(event: string, callback: (data: any) => void): void;
		EventsOff(event: string): void;
	};

	// Wails Go bindings - these are generated by Wails
	function GetDevices(): Promise<import('$lib/types').DeviceConfig[]>;
	function AddDevice(dev: import('$lib/types').DeviceConfig): Promise<void>;
	function UpdateDevice(oldHost: string, dev: import('$lib/types').DeviceConfig): Promise<void>;
	function RemoveDevice(host: string): Promise<void>;
	function ConnectDevice(host: string): Promise<void>;
	function DisconnectDevice(): Promise<void>;
	function GetConnectionStatus(): Promise<import('$lib/types').ConnectionStatus>;
	function ScanNetwork(): Promise<import('$lib/types').NetworkDevice[]>;

	function GetGameSetups(): Promise<import('$lib/types').GameSetup[]>;
	function AddGameSetup(setup: import('$lib/types').GameSetup): Promise<void>;
	function UpdateGameSetup(id: string, setup: import('$lib/types').GameSetup): Promise<void>;
	function RemoveGameSetup(id: string): Promise<void>;
	function SelectFolder(): Promise<string>;
	function UploadGame(setupID: string): Promise<void>;

	function GetInstalledGames(remotePath: string): Promise<import('$lib/types').InstalledGame[]>;
	function DeleteGame(name: string, path: string): Promise<void>;

	function GetSteamGridDBAPIKey(): Promise<string>;
	function SetSteamGridDBAPIKey(key: string): Promise<void>;
	function GetCacheSize(): Promise<number>;
	function ClearImageCache(): Promise<void>;
	function OpenCacheFolder(): Promise<void>;

	function SearchGames(query: string): Promise<import('$lib/types').SearchResult[]>;
	function GetGrids(gameID: number, filters: import('$lib/types').ImageFilters, page: number): Promise<import('$lib/types').GridData[]>;
	function GetHeroes(gameID: number, filters: import('$lib/types').ImageFilters, page: number): Promise<import('$lib/types').ImageData[]>;
	function GetLogos(gameID: number, filters: import('$lib/types').ImageFilters, page: number): Promise<import('$lib/types').ImageData[]>;
	function GetIcons(gameID: number, filters: import('$lib/types').ImageFilters, page: number): Promise<import('$lib/types').ImageData[]>;
}

export {};
