// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDevice(arg1) {
  return window['go']['main']['App']['AddDevice'](arg1);
}

export function AddGameSetup(arg1) {
  return window['go']['main']['App']['AddGameSetup'](arg1);
}

export function ClearImageCache() {
  return window['go']['main']['App']['ClearImageCache']();
}

export function ConnectDevice(arg1) {
  return window['go']['main']['App']['ConnectDevice'](arg1);
}

export function DeleteGame(arg1, arg2) {
  return window['go']['main']['App']['DeleteGame'](arg1, arg2);
}

export function DisconnectDevice() {
  return window['go']['main']['App']['DisconnectDevice']();
}

export function GetCacheSize() {
  return window['go']['main']['App']['GetCacheSize']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetGameSetups() {
  return window['go']['main']['App']['GetGameSetups']();
}

export function GetGrids(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetGrids'](arg1, arg2, arg3);
}

export function GetHeroes(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetHeroes'](arg1, arg2, arg3);
}

export function GetIcons(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetIcons'](arg1, arg2, arg3);
}

export function GetInstalledGames(arg1) {
  return window['go']['main']['App']['GetInstalledGames'](arg1);
}

export function GetLogos(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLogos'](arg1, arg2, arg3);
}

export function GetSteamGridDBAPIKey() {
  return window['go']['main']['App']['GetSteamGridDBAPIKey']();
}

export function OpenCacheFolder() {
  return window['go']['main']['App']['OpenCacheFolder']();
}

export function ProxyImage(arg1) {
  return window['go']['main']['App']['ProxyImage'](arg1);
}

export function RemoveDevice(arg1) {
  return window['go']['main']['App']['RemoveDevice'](arg1);
}

export function RemoveGameSetup(arg1) {
  return window['go']['main']['App']['RemoveGameSetup'](arg1);
}

export function ScanNetwork() {
  return window['go']['main']['App']['ScanNetwork']();
}

export function SearchGames(arg1) {
  return window['go']['main']['App']['SearchGames'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetSteamGridDBAPIKey(arg1) {
  return window['go']['main']['App']['SetSteamGridDBAPIKey'](arg1);
}

export function UpdateDevice(arg1, arg2) {
  return window['go']['main']['App']['UpdateDevice'](arg1, arg2);
}

export function UpdateGameSetup(arg1, arg2) {
  return window['go']['main']['App']['UpdateGameSetup'](arg1, arg2);
}

export function UploadGame(arg1) {
  return window['go']['main']['App']['UploadGame'](arg1);
}
