// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {steamgriddb} from '../models';

export function AddDevice(arg1:config.DeviceConfig):Promise<void>;

export function AddGameSetup(arg1:config.GameSetup):Promise<void>;

export function ClearImageCache():Promise<void>;

export function ConnectDevice(arg1:string):Promise<void>;

export function DeleteGame(arg1:string,arg2:string):Promise<void>;

export function DisconnectDevice():Promise<void>;

export function GetCacheSize():Promise<number>;

export function GetConnectionStatus():Promise<main.ConnectionStatus>;

export function GetDevices():Promise<Array<config.DeviceConfig>>;

export function GetGameSetups():Promise<Array<config.GameSetup>>;

export function GetGrids(arg1:number,arg2:steamgriddb.ImageFilters,arg3:number):Promise<Array<steamgriddb.GridData>>;

export function GetHeroes(arg1:number,arg2:steamgriddb.ImageFilters,arg3:number):Promise<Array<steamgriddb.ImageData>>;

export function GetIcons(arg1:number,arg2:steamgriddb.ImageFilters,arg3:number):Promise<Array<steamgriddb.ImageData>>;

export function GetInstalledGames(arg1:string):Promise<Array<main.InstalledGame>>;

export function GetLogos(arg1:number,arg2:steamgriddb.ImageFilters,arg3:number):Promise<Array<steamgriddb.ImageData>>;

export function GetSteamGridDBAPIKey():Promise<string>;

export function OpenCacheFolder():Promise<void>;

export function ProxyImage(arg1:string):Promise<string>;

export function RemoveDevice(arg1:string):Promise<void>;

export function RemoveGameSetup(arg1:string):Promise<void>;

export function ScanNetwork():Promise<Array<main.NetworkDevice>>;

export function SearchGames(arg1:string):Promise<Array<steamgriddb.SearchResult>>;

export function SelectFolder():Promise<string>;

export function SetSteamGridDBAPIKey(arg1:string):Promise<void>;

export function UpdateDevice(arg1:string,arg2:config.DeviceConfig):Promise<void>;

export function UpdateGameSetup(arg1:string,arg2:config.GameSetup):Promise<void>;

export function UploadGame(arg1:string):Promise<void>;
